### ISSUE TITLE
invalid character in resolvable name

### ISSUE THREAD

**Issue by probonopd** [probonopd/switchers-compat#1]
Having a binary called `apt-get` with a `-` character in the `provides` section of the `.PackageInfo` file results in:

```
~/switchers-compat> ./make-hpkg.sh 
+ package create -b switchers_compat.hpkg
Parse error in .PackageInfo(23:12) -> invalid character in resolvable name
```

Is this a bug in the `package` tool @waddlesplash?

**Comment by waddlesplash** [comment]
Nope, the `-` character is not allowed in provides, for a variety of reasons. Use `_` in its place.

**Comment by probonopd** [comment]
Also I wonder whether I really have to add all those `cmd:` manually or whether there is an automatic wildcard - everything that has executable bits in `bin`...

**Comment by probonopd** [comment]
The command is called `apt-get` and having exactly that name of the placeholder script is the whole point of it...

**Comment by waddlesplash** [comment]
Well the file can have that name, the provide cannot. This is true of any provide. Commands with `-` in them are rather rare -- in fact `apt-get` is now deprecated and `apt` is the replacement, yes? :)

You have to add provides manually, yes. In HaikuPorter this serves as a double-check -- i.e. that all the commands specified really are in the package, and that there are not more than specified. This way if a new version of a port starts shipping a command that should not be in the base package, you will notice because HaikuPorter will bail out with an error message...

**Comment by waddlesplash** [comment]
(The decision about how provides and package names are processed internally that lead to `-` being disallowed in package names and provides/requires was maybe not the best technical decision, but it's relatively rare we run into it anyway...)
